name: Temp Continuous Intrgation

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
      
      - name: "Setting up node"
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - name: "Install Dependencies"
        run: npm i
      
      - name: "Test"
        run: npm run test